// Code generated by "stringer -type=ErrorType"; DO NOT EDIT.

package main

import "fmt"

const _ErrorType_name = "ExceedRecursionLimitUnmatchedBraceUnknownReferenceInvalidDollarSequence"

var _ErrorType_index = [...]uint8{0, 20, 34, 50, 71}

func (i ErrorType) String() string {
	if i < 0 || i >= ErrorType(len(_ErrorType_index)-1) {
		return fmt.Sprintf("ErrorType(%d)", i)
	}
	return _ErrorType_name[_ErrorType_index[i]:_ErrorType_index[i+1]]
}
